############################################################## MAKEFILE FOR STUB

arch = stub
cpu = stub
gnuArch = stub
base_ccopts =

include ../../makefile.in
include ../../arch/stub/loader/makefile.in
